services:

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/app:/app/app
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: db_admin
      POSTGRES_PASSWORD: db_admin
    volumes:
      - ./scripts/postgress-init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - todolist_db:/var/lib/postgresql
    ports:
      - 5435:5432

  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules/
    ports:
      - 5173:5173

volumes:
  todolist_db: